[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google-cloud/text-to-speech"]
  # Increase function timeout to 60 seconds
  timeout = 60

[[redirects]]
  from = "/api/audio/generate"
  to = "/.netlify/functions/generateAudio"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Copy favicon to root of site
[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins.inputs]]
copy = [
  { from = "public/favicon.ico", to = "build/favicon.ico" }
]
