services:
  - type: web
    name: audiomax-server
    env: node
    buildCommand: npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: DATABASE_URL
        value: mongodb+srv://arcanadraconi:9cshn8xjVOFEIQyS@audiomax.q25pz.mongodb.net/?retryWrites=true&w=majority&appName=audiomax
      - key: DATABASE_NAME
        value: audiomax
      - key: JWT_SECRET
        value: 3ebe4e6cb563b8123e3bc2c01d86ff5d64f9520795bb28e270e227c53dda6ac59535aa105ef48b4fc910ed42865787c46ffbfe7384d2707c0455f977695ea118
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PRODUCTION_CLIENT_URL
        value: https://audiomax.netlify.app
      - key: COOKIE_SECRET
        value: dev_cookie_secret_123
      - key: SESSION_SECRET
        value: dev_session_secret_123
      - key: CORS_ALLOWED_ORIGINS
        value: https://audiomax.netlify.app
      - key: GOOGLE_PROJECT_ID
        value: audiomax-440801
      - key: GOOGLE_CLIENT_EMAIL
        value: text2speech@audiomax-440801.iam.gserviceaccount.com
      - key: GOOGLE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIxGnbLnGFYaE2\n0tlUaJFn8PI1/0NjGQT5TS1ap/yfh7XsQ2Sq+f/QDIVrXMmuAbWIkwLT6rPmHH/K\n7iZFlnSwaP9ZAiL9qoBLm2yl5NscfN5UdqdDYhgr2YgsRYy0J4WzRVtkr62Ifvcq\n1vwnQ/X9nYmcxpQu9e0r1KmIlVvfmq4/yggBqHlUjerVLjhA5NPRTBMWanmEFk89\nidxAvFDCbdVFtK3zeGHdcdI6G28K35wshV2t1PM8xsmN473arflLUCA0mXGA+lZq\nnjwtqy4vdm/KdzFvWGQ2sTUpLH4oTc/D4EsYRO//vM4ZbjKtJ/XJBcQ6FlUmieHu\n/XY7sRKPAgMBAAECggEAATita74NJVfPMMo7E0iSF9Dc4wgsVtChAMi/5VS9aKrm\np/Nrh0CuxZ5AQMzrhoRBs2VpkG+q/Lw/k4V5h4ni0uMI77CdTfSnLn36pUU0h05S\nIbi/hJGJzMYMf/6sLRgbRikAyO3EraWSdttUfLdVPV/cdjO+VL8afZJnFJkVgB04\nNVk3LKMeiWQ7hBdL7H0DgN7kPuFoFTXg2iPEDDLAW7J29hQ+YPxycLQS+AS2ir6+\nhtOP7WEK0ONdZZx8p6kCROPi+kzZbG4/8y7PAoTYnQ2xSjLsStbUKLNrNTjMndTK\n35wbIqAsbTSXPfGg/l6IeIPJWWTDgQF9Iog7Np1d6QKBgQD2S1KRyQukqWfHHCmS\nidZfOR4/JMnGzkcveOiKWf6mkoQoxXbcupVWLvir0v2CUxvXVqxKvH73dfQMqCgN\nXJSctjNMVsjqRsagvfOSIOWwH/BtP3ayPqTsnKOQdUb9sIU88MBbtO5GuYmnNslX\nHTjkIGGe4NG7NB0u5W3+89Pj3QKBgQDQrc2qEAtY5QNcL0Hx1S3mIHNoOHrc1YKO\nsZzxX93Q2iFfrD88R0RkVbPKMWLo20agXqYy2L4KtUaa4eheeS2k/Qea1tCujCVv\nRGZ6318OEfFfqrUtRoZ/ukknZQ8CBmVP3IHu0rg5VSWSOKus4bwE7dgxt8uffkKc\nt6+XONevWwKBgCv8F6rhdKrbdiUg6mu5Igevc69jKoXOoPfhZ+YNXGTzFZcSbL/O\nsozJpq9I5u03WmmCmRJfx2z6K7N29HAucHvsLg0cEpWEPkTGp5EZPuvNSGq6QsBi\nX6HB95P83cjAlYrkk/XMwiDvUZ4DMsHT/iz/e2+cRthf3jZZ0uMNOHIhAoGAPDpd\niH7W95IpdRrCmqyfcbLd/C+I7mHFK7ABjvzPRW8fgMBzA8/B4n+Fw46bcH+RE8od\nh8FcoDSPqzYWXeX1kY/h+QOU+TvDtih0t3PuuF3fX3AimG2pdgXrBS66tSfpZ7JJ\n4gb5WrrDfD9U9TG1lWqcIkVcxKypRxgQ2sFyJs8CgYEAn8O/6XvHXjgp16VKyym7\nblO5n9upBSe8hzf8/T/N50tcR36TKjnABAdZwJspQYNmFD1DJWQHPAw4AOaD4fzJ\ngT5kOycHCkSkv8qJwmpzxRNs6HlU8onsG4hxhlEZ5DHWL0pTDwUykfOKmaMibG9P\nx39Ny3IUgDHAh/mf/GQN5nw=\n-----END PRIVATE KEY-----\n"
      - key: GOOGLE_CLIENT_ID
        value: 827680900052-dm36j76jhcqh96k78gl89rc3p9ig4d2n.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_PRIVATE_KEY_ID
        value: b5547b989eecb72610b5b2cca072f3a3bda1275b
      - key: VOICE_API_TYPE
        value: google
      - key: SMTP_HOST
        value: sandbox.smtp.mailtrap.io
      - key: SMTP_PORT
        value: "2525"
      - key: SMTP_USER
        value: 26253160108c29
      - key: SMTP_PASS
        value: "********0912"
      - key: SMTP_FROM_EMAIL
        value: noreply@audiomax.ai
      - key: SMTP_FROM_NAME
        value: MaxAudio Dev
      - key: ENABLE_VOICE_CLONING
        value: "true"
      - key: ENABLE_CUSTOM_VOICES
        value: "true"
      - key: ENABLE_ANALYTICS
        value: "true"
      - key: ENABLE_PUSH_NOTIFICATIONS
        value: "false"
      - key: DEFAULT_STORAGE_LIMIT
        value: "104857600"
      - key: DEFAULT_REQUEST_LIMIT
        value: "100"
      - key: DEFAULT_AUDIO_LENGTH
        value: "60"
      - key: STRIPE_SECRET_KEY
        value: sk_test_51QJcWMGTXKQOsgznsyOIaa5W9rxYfcTd7nHtCT2FHKILa7zCqsQwSOFgzUwSQma3LldyQCDIlARKxYxNzoDh2iSc008s9MNZkk
      - key: STRIPE_PRICE_ID_PRO_MONTHLY
        value: price_1QJciwGTXKQOsgznGHYwmY9o
      - key: STRIPE_PRICE_ID_PRO_YEARLY
        value: price_1QJcixGTXKQOsgzn5K0IlyR0
      - key: STRIPE_PRICE_ID_PREMIUM_MONTHLY
        value: price_1QJcixGTXKQOsgzntFkccdTg
      - key: STRIPE_PRICE_ID_PREMIUM_YEARLY
        value: price_1QJcixGTXKQOsgznqRPzlJJX
